package org.openmrs.module.feedback;
// Generated May 17, 2011 2:52:39 PM by Hibernate Tools 3.2.1.GA



/**
 * FeedbackSeverity generated by hbm2java
 */
public class FeedbackSeverity  implements java.io.Serializable {

    public static final long serialVersionUID = 113222232L;

     private int index;
     private String severity;

    public FeedbackSeverity() {
    }

    public FeedbackSeverity(int index, String severity) {
       this.index = index;
       this.severity = severity;
    }
   
    public int getIndex() {
        return this.index;
    }
    
    public void setIndex(int index) {
        this.index = index;
    }
    public String getSeverity() {
        return this.severity;
    }
    
    public void setSeverity(String severity) {
        this.severity = severity;
    }




}


